name: build
on: [push]
jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.8' 
            architecture: 'x64' 
      - name: Show Python version
        run: python --version
      - name: Install environment
        run: | 
          pip install flit==3.7.1
          flit install
      - name: Building library
        run: |
          export SOURCE_DATE_EPOCH=$(date +%s)
          flit build
      - name: Codeanalysis
        run: prospector --profile .prospector.yaml --zero-exit
      - name: Run unit test
        run: |
           coverage run -m unittest
           coverage report
         