name: build
on: [push]
jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.7' 
            architecture: 'x64' 
      - name: Show Python version
        run: python --version
      - name: Install environment
        run: |
             python -m venv env
             source env/bin/activate
             pip install -r build_requirements.txt
      - name: Run unit test
        run: python -m unittest
         